version: "3.9"

services:
  db:
    image: postgres:15
    container_name: test_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: test_bot
    ports:
      - "5432:5432"
    volumes:
      - /root/test_bot/postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test_app
    restart: always
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "9090:9090"
    environment:
      DATABASE_URL: "postgresql://postgres:12345@db:5432/test_bot?schema=public"
    command: >
      sh -c "
        npx prisma generate &&
        npx prisma migrate deploy &&
        node dist/src/main.js
      "

volumes:
  postgres_data:
