# --- Stage 1: Build ---
FROM node:22-alpine AS builder

WORKDIR /app

# Nest CLI global o‘rnatamiz (build uchun shart)
RUN pnpm install -g @nestjs/cli

# Dependency fayllarni ko‘chiramiz
COPY package*.json ./

# Dependencies o‘rnatamiz
RUN pnpm install

# Source fayllarni ko‘chiramiz
COPY . .

# Prisma clientni generatsiya qilamiz
RUN npx prisma generate

# NestJS buildni yaratamiz
RUN pnpm run build


# --- Stage 2: Run ---
FROM node:22-alpine AS runner

WORKDIR /app

COPY package*.json ./
RUN npm install --only=production

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/prisma ./prisma

EXPOSE 9090

CMD ["node", "dist/src/main.js"]

